services:
  db:
    image: postgres:15
    container_name: ise_as_db
    environment:
      POSTGRES_USER: ise_admin
      POSTGRES_PASSWORD: ise_password
      POSTGRES_DB: ise_as_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
