package com.iseas.ise_as_backend.model;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    UNDER_REVIEW,
    INCOMPLETE,
    AWAITING_DOCUMENTS,
    READY_FOR_REVIEW,
    ACADEMIC_REVIEW,
    INTERVIEW_REQUIRED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    COMMITTEE_REVIEW,
    WAITLISTED,
    ACCEPTED,
    REJECTED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    ENROLLMENT_PENDING,
    ENROLLED
}
