package com.iseas.ise_as_backend.model;

public enum Role {
    PARENT,
    APPLICANT,
    ADMISSIONS_OFFICER,
    REVIEWER,
    INTERVIEWER,
    ADMISSIONS_COMMITTEE,
    PRINCIPAL,
    REGISTRAR,
    ADMINISTRATOR,
    SCHOOL_ADMINISTRATOR,
    SUPER_ADMIN,
    CODAFRIQA_SUPPORT
}
